- name: Copy vault certificate
  copy:
    src: "{{ vault_certificate_file }}"
    dest: "{{ vault_config_dir }}/cert.pem"
    mode: 0700
    owner: "{{ vault_system_user }}"

- name: Copy vault private key
  copy:
    src: "{{ vault_private_key_file }}"
    dest: "{{ vault_config_dir }}/key.pem"
    mode: 0700
    owner: "{{ vault_system_user }}"
