---
- name: Update System
  yum:
    name: '*'
    state: latest

- name: Install misc packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - vim
    - wget
    - unzip

- name: Create local tmp directory if does not exist
  file:
    path: "{{ tmp_working_dir }}"
    state: directory
    mode: 0770

- name: Download Vault binary
  get_url:
    url: "{{ hashicorp_vault_source }}"
    dest: "{{ tmp_working_dir }}/vault.zip"
    mode: 0660

- name: Extract vault binary
  unarchive:
    src: "{{ tmp_working_dir }}/vault.zip"
    remote_src: yes
    dest: /usr/local/sbin/
    mode: 0755

- name: Add mlock capability
  capabilities:
    path: /usr/local/sbin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Create vault user
  user:
    name: "{{ vault_system_user }}"
    system: yes
    state: present
    shell: /usr/bin/false

- name: Create configuration directory
  file:
    path: "{{ vault_config_dir }}"
    mode: 0750
    state: directory
    owner: "{{ vault_system_user }}"
    group: "{{ vault_system_group }}"

- name: Update hostname
  hostname:
    name: "{{ vault_hostname }}"
  when: vault_hostname is defined

- name: Update local lookup
  lineinfile:
    path: /etc/hosts
    regexp: "{{ vault_hostname }}"
    line: "{{ ansible_host }}   {{ vault_hostname }}"
    state: present
  when: vault_hostname is defined

- name: Include filesystem backend config
  include_tasks: filesystem_backend.yml
  when: vault_storage_backend == "filesystem"

- name: Copy configuration file
  template:
    src: service.hcl.j2
    dest: "{{ vault_config_dir }}/service.hcl"
    mode: 0700
    owner: "{{ vault_system_user }}"
    group: "{{ vault_system_group }}"

- name: Deploy SSL
  include_tasks: deploy_ssl.yml
  when: vault_tls_enabled == True

- name: Configure systemd service
  template:
    src: vault.service.j2
    dest: /lib/systemd/system/vault.service
    mode: 0700

- name: Start vault service
  systemd:
    name: vault
    state: started
    daemon_reload: True
    enabled: yes
